resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: apache
      namespace: clicars
    spec:
      template:
        spec:
          containers:
          - name: apache
            image: clicarstest/apache:develop-a9e4ce4869a9926178b2bda0bbd6cee57aab21ca
