apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: clicars
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    spec:
      containers:
      - name: apache
        image: clicarstest/apache:1.0
        ports:
        - containerPort: 80
