name: build and push
on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'k8s/**'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: clicarstest/${{ env.REPOSITORY_NAME }}
          
      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Edit image on manifests repository
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          IMAGE: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
        run: |
          curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GH_TOKEN_ACTIONS }}" \
              --data '{"event_type": "change_image", "client_payload": { "repository": "${{ env.REPOSITORY_NAME }}", "branch": "'"$BRANCH"'", "image": "'"$IMAGE"'", "actor": "'"$GITHUB_ACTOR"'" }}' \
              https://api.github.com/repos/ramiroduarteavalos/${{ env.REPOSITORY_NAME }}/dispatches
